Repository APAC-Solution-Challenge-2025/Backend, pull requests merged in 2025-05, with the labels that each got.

#5 Feat: 캘린더 조회 기능 개발
  apac-solution-challenge/apac/build.gradle
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/controller/CalendarController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/domain/DailyGoalAchieved.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/domain/DailyGoalAchievedId.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/dto/CalendarDay.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/dto/CalendarResponse.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/repository/DailyGoalAchievedRepository.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/service/CalendarService.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/AuthController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/domain/User.java
  apac-solution-challenge/apac/src/main/resources/application.properties
Labels: feat, ✔️리뷰 완료

#7 Feat: Google OAuth 마무리 및 Firebase로 수정 + Swagger로 API 명세
  apac-solution-challenge/.idea/dataSources.xml
  apac-solution-challenge/apac/.gitignore
  apac-solution-challenge/apac/Dockerfile
  apac-solution-challenge/apac/build.gradle
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/FirebaseConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/JwtConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SecurityConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SwaggerConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/AuthController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/UserController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/domain/User.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/UserResponseDto.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/repository/UserRepository.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtFilter.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtUtil.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/UserService.java
  apac-solution-challenge/apac/src/main/resources/application.properties
  apac-solution-challenge/docker
Labels: feat, ✔️리뷰 완료

#8 Refactor: 데이터베이스 변경에 따른 calendar 변경
  apac-solution-challenge/.idea/.gitignore
  apac-solution-challenge/.idea/apac-solution-challenge.iml
  apac-solution-challenge/.idea/compiler.xml
  apac-solution-challenge/.idea/dataSources.xml
  apac-solution-challenge/.idea/gradle.xml
  apac-solution-challenge/.idea/misc.xml
  apac-solution-challenge/.idea/modules.xml
  apac-solution-challenge/.idea/modules/apac.main.iml
  apac-solution-challenge/.idea/vcs.xml
  apac-solution-challenge/apac/.gitignore
  apac-solution-challenge/apac/Dockerfile
  apac-solution-challenge/apac/build.gradle
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/controller/CalendarController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/domain/DailyGoalAchieved.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/dto/CalendarDayDTO.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/dto/CalendarResponseDTO.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/service/CalendarService.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/FirebaseConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/JwtConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SecurityConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SwaggerConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/WebConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/AuthController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/UserController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/domain/User.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/AuthResponse.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/UserInfoDto.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/UserResponseDto.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtFilter.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtUtil.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/UserService.java
  apac-solution-challenge/apac/src/main/resources/application.properties
  apac-solution-challenge/apac/src/test/java/com/example/apac/calendar/calendarControllerTest.java
  apac-solution-challenge/docker
Labels: 🔥리뷰 요청, refactor

#11 Feat: Gemini API를 이용한 챗봇 구현
  apac-solution-challenge/.idea/.name
  apac-solution-challenge/.idea/compiler.xml
  apac-solution-challenge/.idea/misc.xml
  apac-solution-challenge/.idea/modules.xml
  apac-solution-challenge/apac/.gitignore
  apac-solution-challenge/apac/build.gradle
  apac-solution-challenge/apac/src/main/java/com/example/apac/calendar/dto/CalendarResponseDTO.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/FirestoreConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/JwtConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SecurityConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/GeminiController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/domain/ChatMessage.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/domain/User.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/ChatRequest.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtFilter.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtUtil.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/GeminiService.java
  apac-solution-challenge/apac/src/main/resources/application.properties
  apac-solution-challenge/apac/src/test/java/com/example/apac/ApacSolutionChallengeApplicationTests.java
Labels: feat, ✔️리뷰 완료

#14 Feat: 사용자 상태정보 DB에 저장
  apac-solution-challenge/.idea/compiler.xml
  apac-solution-challenge/.idea/gradle.xml
  apac-solution-challenge/.idea/modules.xml
  apac-solution-challenge/.idea/modules/apac.main.iml
  apac-solution-challenge/apac/Dockerfile
  apac-solution-challenge/apac/build.gradle
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/FirebaseConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/FirestoreConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SecurityConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/WebConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/AuthController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/HealthDataController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/UserController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/HealthDataDto.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/GeminiService.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/HealthDataService.java
  apac-solution-challenge/apac/src/main/resources/application.properties
Labels: feat, 🔥리뷰 요청

#15 Feat: 사용자 맞춤형 Gemini 프롬프트 수정
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/GeminiController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/GeminiService.java
Labels: feat, 🔥리뷰 요청

#17 Refactor: AuthController, HealthDataController 수정
  apac-solution-challenge/apac/build.gradle
  apac-solution-challenge/apac/deps.txt
  apac-solution-challenge/apac/src/main/java/com/example/apac/ApacSolutionChallengeApplication.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/config/SecurityConfig.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/AuthController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/controller/HealthDataController.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/dto/HealthDataDto.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/security/JwtFilter.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/HealthDataService.java
  apac-solution-challenge/apac/src/main/java/com/example/apac/service/UserService.java
Labels: 🔥리뷰 요청, refactor
